apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/notification-service:latest
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: AWS_REGION
            - name: SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SQS_QUEUE_URL
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SMTP_PORT

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: SMTP_PASS
